# Generated by Django 4.0.2 on 2022-02-22 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_products_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='store',
            new_name='tore',
        ),
    ]
