# Generated by Django 4.0.2 on 2022-02-22 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_store_products_tore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='tore',
            new_name='Store',
        ),
    ]
